# ======================================================
#  Mob Kill Effects v1.4
#
#  Author: GamerBoss101
#
#  Description: Every Mob you kill gives you a random effect. 
#
# ======================================================
#
# Potion Time runs on ingame ticks ( 1 second = 20 ingame ticks )
#   
# Example: 30 seconds = 600 ticks || 60 seconds = 1200 ticks
#
# Type the amount of tick you want the potion to last for.
#

potionEffect_time: '600'